import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@styles/globals.css";
import Providers from "@/components/header/Providers";
import Navbar from "@/components/header/Navbar";
import Footer from "@/components/footer/Footer";
// import { ThemeProvider } from "next-themes";
// import Providers from "@/components/Navbar/Providers";
// import ThemeSwitcherBtn from "@/components/Navbar/_ThemeSwitcher";
// import { useContext } from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "@javiiccode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="bg-gradient-radial " />
        {/* <div className="bg-gradient-linear" /> */}
        <Providers>
          <Navbar />
          <main className="min-h-screen min-w-full flex justify-center relative z-10 ">
            {/* prose */}
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
